---
- name: Setup Docker-Server
  hosts: localhost
  remote_user: root

  tasks:
  - name: Hello Variable
    debug:
      msg: "{{ mein_wichtiger_hinweis }}"

  - name: print mit Loop
    user: name="{{ item }} state=present groups=wheel
    loop:
      - anna
      - paul
    msg: "{{ item }}"
