---
- name: Setup Docker-Server
  hosts: localhost
  remote_user: root

  tasks:
  - name: Hello Variable
    debug:
      msg: "{{ mein_wichtiger_hinweis }}"

  - name: print mit Loop
    debug: name="{{ item }} state=present groups=wheel
    loop:
      - Euro-League
      - Champions-League
    msg: "moeglich ist {{ item }}"
