---
- name: Setup Docker-Server
  hosts: localhost
  remote_user: root

  tasks:

  - name: Hello Server
    debug:
      msg: "Hello  Europapokal!" 
      
  - name: Erstelle eine Datei
      path: /tmp/eineDatei
      state: touch
