---
- name: Setup Docker-Server
  hosts: localhost
  remote_user: root

  tasks:

  - name: Hello Server
    debug:
      msg: "Hello  Europapokal!" 
      
  - name: Erstelle eine Datei
    file:
      path: /tmp/eineDatei
      state: touch

  - name: Erstelle einen Ordner
    file:
      path: /tmp/einenOrdner
      state: directory    
      
  - name: Erstelle einen Ordner
    file:
      path: /tmp/einenOrdner
      state: directory
